### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Ryce** [ekristen/aws-nuke#385]
aws-nuke run

```console
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1024e212c]

goroutine 1 [running]:
main.main.func1()
	github.com/ekristen/aws-nuke/v3/main.go:28 +0x60
panic({0x107c13680?, 0x10cdd67b0?})
	runtime/panic.go:785 +0x124
github.com/ekristen/libnuke/pkg/config.(*Config).ResolveDeprecations(0x14000028000)
	github.com/ekristen/libnuke@v0.19.2/pkg/config/config.go:240 +0x6c
github.com/ekristen/libnuke/pkg/config.New({{0x1064a45a1, 0xb}, 0x140003ff030, 0x14000012ea0, 0x0, 0x0})
	github.com/ekristen/libnuke@v0.19.2/pkg/config/config.go:118 +0x2cc
github.com/ekristen/aws-nuke/v3/pkg/config.New({{0x1064a45a1, 0xb}, 0x140003ff030, 0x14000012ea0, 0x0, 0x0})
	github.com/ekristen/aws-nuke/v3/pkg/config/config.go:18 +0x44
github.com/ekristen/aws-nuke/v3/pkg/commands/nuke.execute(0x1400013e3c0)
	github.com/ekristen/aws-nuke/v3/pkg/commands/nuke/nuke.go:74 +0x3bc
github.com/urfave/cli/v2.(*Command).Run(0x140004122c0, 0x1400013e3c0, {0x140003fbe50, 0x1, 0x1})
	github.com/urfave/cli/v2@v2.27.5/command.go:276 +0x600
github.com/urfave/cli/v2.(*Command).Run(0x140004129a0, 0x1400013e280, {0x14000146000, 0x2, 0x2})
	github.com/urfave/cli/v2@v2.27.5/command.go:269 +0x83c
github.com/urfave/cli/v2.(*App).RunContext(0x14000018000, {0x108efcc90, 0x10ce17740}, {0x14000146000, 0x2, 0x2})
	github.com/urfave/cli/v2@v2.27.5/app.go:333 +0x51c
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.27.5/app.go:307
main.main()
	github.com/ekristen/aws-nuke/v3/main.go:50 +0x1e0
```
	
This is just on the run command, nothing special happening here

**Comment by ekristen** [comment]
You only ran `aws-nuke run`? What version? What does your `config.yaml` look like? There must have been one in the directory in which you ran the command.

**Comment by ekristen** [comment]
@Ryce please provide your config.yaml.

**Comment by ekristen** [comment]
@shblue21 your config is invalid, add `{}` to the end of the account at a minimum to get started. I'll try and put some guards in in the mean time.

```
regions:
  - global

accounts:
  "0964xxxxxxxx": {}
```
